### ISSUE TITLE
In-app purchase system to make premium icon requests

### ISSUE THREAD

**Issue by afollestad** [jahirfiquitiva/PaperBoard#15]

**Comment by jahirfiquitiva** [comment]
When doing this, please add the possibility to use them or not.
I mean, like a boolean or something for if user wants to include it or not in its app.

This will be useful, because, for example, I can't create a Google merchant account, or wallet account or PayPal, because of country + bank restrictions.

Hope you understand. Thanks in advance.

**Comment by asdfasdfvful** [comment]
In regards to that, you could (if you wanted) use the same boolean that  is used in toggling the license  check, since it would have to be from the play store anyways to use the IAP. Another choice is to add it so that if they boolean is false, the donation part will simply go towards a paypal account (or any other link) which is not dependent on google services.

I'm sure you have your own idea, but here is an example just in case

https://github.com/sufficientlysecure/android-donations-lib

Boolean could also be easily toggled with flavours for facilitated testing.

**Comment by afollestad** [comment]
I'm actually planning to use the same library I use to accept donations in
Cabinet.

But good point about the license check.

**Comment by afollestad** [comment]
Donations in an app at all violate Google's policies though. So this is more like a paid request than a donation.

**Comment by jahirfiquitiva** [comment]
I find the use of the same boolean as license checker, not good at least for me, because I want users to download the app from play store only, as it improves the statistics. So I will use license checker, but not the premium requests stuff.

**Comment by asdfasdfvful** [comment]
Well that's where the boolean comes in. If you have an app on the play store, you my as well add the license in, and as the boolean is true it'll use google IAP. You can still have donations, as long as they are through google, just like how it is in Cabinet. Or if not, maybe you can link me to the restrictions?

It's just that if you are testing or don't have it uploaded on the play store, you don't want the license nor the IAP as they won't work. In that case the link will work. But seeing what Jahir wrote, I guess you could split it into two.

And btw, whatever library you have for Cabinet is better, as it actually allows for proper payment consumptions (y).
