### ISSUE TITLE
Switch Fragment Error

### ISSUE THREAD

**Issue by helmifluida** [jahirfiquitiva/PaperBoard#24]
getSupportFragmentManager().beginTransaction()
                .setCustomAnimations(android.R.anim.slide_in_left, android.R.anim.slide_out_right)
                .replace(R.id.main, Fragment.instantiate(MainActivity.this,
                        "com.android.fluida.summericon.fragment." + fragment + "Fragment"))
                .commit();

How i get Id.Main ??

switchFragment(1, thaApp, "New");

Force close again :( im sorry

**Comment by jahirfiquitiva** [comment]
@helmifluida 

First of all, issues in GitHub are supposed to be issues with the original source. Once you start modifying it, every issue is your responsibility, because if you follow the tutorial, there won't be issues.

Now, as the issues you have posted lately have been all related with your own app, I will ask you to stop posting them here. Is not the source which has the issues, but your app.

All your issues from now on, will be simply closed and/or ignored.

So, join this Google+ community where help is provided when issues like these happen.
http://tiny.cc/PaperBoardCommunity

Once you get there, you can ask for help for anything related to PaperBoard.

Now, to answer your question, the right code is:

```javascript
getSupportFragmentManager().beginTransaction()
                .setCustomAnimations(android.R.anim.slide_in_left, android.R.anim.slide_out_right)
                .replace(R.id.main, Fragment.instantiate(MainActivity.this,
                        "com.jahirfiquitiva.paperboard.fragments." + fragment + "Fragment"))
                .commit();
```

You don't have to replace anything in it, because otherwise the fragments won't be found and the app will crash.

Follow the tutorial exactly as it is. I'm sure I didn't mention you have to edit this line, so don't do it.

I will be waiting for you in the community if you need extra help. Good luck.
